<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CientsHandling\" />
    <Folder Include="GameHandling\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestClient\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.4" />
  </ItemGroup>

</Project>
